# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: mambaorg/micromamba:latest
stages:
- audit
- test

sast:
  stage: audit
include:
- template: Security/SAST.gitlab-ci.yml

test:
  stage: test
  needs: []
  script:
  - micromamba install -y -n base -c conda-forge -f requirements.txt pytest-cov
  - pip install -e .[xarray]
  - py.test -v -k "not benchmark" --cov --cov-report term-missing --junitxml=report.xml multimodemodel
  artifacts:
    when: always
    reports:
      junit: report.xml


lint:
  stage: test
  needs: []
  script:
  - micromamba install -y -n base -c conda-forge flake8 flake8-docstrings
  - flake8 .
